/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "worlds": "世界",
    "You can now force the dead you harvest to work for your rapidly growing empire. While Astral Enslavement is active, time goes 10x slower,\n                                and you won't gain any corpses; instead, those tortured, miasmic souls will suffer tirelessly making bricks for your most unholy of foundations.": "你现在可以强迫你收获的死者为你快速发展的帝国工作。 当星体奴役激活时，时间会慢 10 倍，\n 你不会得到任何尸体； 相反，那些饱受折磨的瘴气灵魂将不知疲倦地为你最邪恶的地基砌砖。",
    "Cost: {{ formatUR(getRefineryCost(), 0) }} ": "成本: {{ formatUR(getRefineryCost(), 0) }} ",
    ". (@ {{ getAstralNerf() }}x slower time speed": ". (@ {{ getAstralNerf() }}x 更慢的时间速度",
    "You will gain {{ formatWhole(getEmittersPerLevel()) }} additional emitters.": "你将获得 {{ formatWhole(getEmittersPerLevel()) }} 额外发射器.",
    "Turn All Off": "全部关闭",
    "Turn All On": "全部开启",
    "Ultra-Solar": "超太阳能",
    "unassigned emitters.": "未分配的发射器。",
    "Unit autobuyers attempt to buy in order from priority 1 to priority 8.": "单位自动购买者尝试按照优先级 1 到优先级 8 的顺序购买。",
    "Unit Boost": "单位提升",
    "Unit Mult": "单位乘数",
    "Unit tier corpse multipliers get a boost based on unspent time crystals.": "单位层尸体乘数会根据未使用的时间水晶获得提升。",
    "Unit Type": "单位类型",
    "UNITS": "单位",
    "UNLEASH DEATH": "释放死亡",
    "Unlock bulk autobuyers permanently, and crystal gain is boosted based on your nekro-photons.": "永久解锁大宗自动购买者，水晶增益会根据你的 nekro-photons 得到提升。",
    "Unlock fast autobuyers permanently, and the buildings/construction tabs are never reset on sacrifice (except bricks and resources).": "永久解锁快速自动购买者，并且建筑物/建筑标签永远不会因牺牲而重置（砖块和资源除外）。",
    "Unlock the second row of Dead Sun upgrades, and increase base emitters gained per refinery level from 1 -> 2.": "解锁第二排死日升级，每炼油厂等级获得的基础发射器从 1 -> 2 增加。",
    "Unlock the second row of Galactic Vortex upgrades.": "解锁第二排银河漩涡升级。",
    "Unlock the world prestige autobuyer permanently.": "永久解锁世界声望自动购买者。",
    "Void Research production is multiplied by the log of your current bricks/sec.": "虚空研究产量乘以您当前砖块/秒的日志。",
    "void research.": "无效的研究。",
    "w: Buildings Tab;": "w：建筑物选项卡；",
    "When you begin a research project, you do a galaxy respec and time respec,": "当你开始一个研究项目时，你会做一个银河系和时间方面的研究，",
    "without any exceptons from milestones, achievements past the first row, or project rewards": "里程碑、超过第一行的成就或项目奖励没有任何例外",
    "World Prestige": "世界威望",
    "World Prestige resets your": "世界声望重置你的",
    "World Refiner": "世界精炼者",
    "x as fast.": "x 一样快。",
    "x bonus to corpse gain.": "x 尸体增益加成。",
    "x slower time speed": "x 较慢的时间速度",
    "You are gaining": "你正在获得",
    "You are harvesting": "你在收获",
    "you are producing": "你正在生产",
    "You are producing": "你在生产",
    "You can only buy one galaxy upgrade from each tree and from each row (the normal upgrade requirements are suspended).": "您只能从每棵树和每行购买一个星系升级（暂停正常升级要求）。",
    "You can only buy one galaxy upgrade from each tree and from each row.": "您只能从每棵树和每一行购买一个星系升级。",
    "You can only use one galaxy tree.": "您只能使用一棵星系树。",
    "You can't take both branches in the same tree; buying an upgrade in the 2nd row will lock out the two in the other branch.": "你不能在同一棵树上取两个分支；在第二排购买升级将锁定另一个分支中的两个。",
    "you don't have any past runs!": "您没有任何过去的跑步记录！",
    "You gained": "你获得了",
    "You have achieved": "你已经达到",
    "You have completed": "您已完成",
    "You have exterminated": "你已经消灭了",
    "You have formed": "你已经形成",
    "YOU HAVE GONE BEYOND.": "你已经超越了。",
    "You have the knowledge needed to craft The Ark, but your thirst has not been quenched.": "你拥有制作方舟所需的知识，但你的渴望并没有被解渴。",
    "You produce 1% of your corpse production while in astral enslavement.": "在星界奴役期间，你生产 1% 的尸体。",
    "You produce your astral brick production ^0.9 outside of astral enslavement (still affected by the astral time nerf).": "你在星界奴役之外生产你的星界砖生产^0.9（仍然受到星界时间削弱的影响）。",
    "You receive a message from beyond.": "你收到来自彼岸的消息。",
    "You will keep": "你会保持",
    "Your": "您的",
    "Your achievements and achievement rewards are permanent. They persist through": "您的成就和成就奖励是永久的。他们坚持通过",
    "your acolytes chant into the astral abyss, boosting your astral brick gain by": "你的追随者向星界深渊吟唱，提高你的星界砖增益",
    "Your Anti Time Emitters speed up astral time by": "你的反时间发射器加速星光时间",
    "Your Refinery is level": "你的炼油厂等级是",
    "Your refinery level multiplies the anti time effect.": "你的炼油厂等级乘以反时间效果。",
    "Your refinery level multiplies the true time effect.": "您的炼油厂级别会乘以真实的时间效果。",
    "Your total galaxies multiply unit production multipliers.": "你的星系总数乘以单位生产乘数。",
    "Your True Time Emitters speed up normal time by": "您的真实时间发射器将正常时间加快",
    "Your unholy hordes have forged": "你的邪恶部落已经锻造",
    "zombies": "僵尸",
    "Zombies": "僵尸",
    "Zombies also produce Sun Eaters at a very greatly reduced rate (sqrt(log)).": "僵尸也以非常低的速率（sqrt（log））产生食日者。",
    "Recrystallization": "重结晶",
    "Refinery Efficiency": "炼油厂效率",
    "Requires": "需要",
    "Requires at least 10 exterminated worlds": "需要至少 10 个已灭绝的世界",
    "Requires at least 1e20 corpses": "需要至少 1e20 具尸体",
    "Reset for": "重置为",
    "resets.": "重置。",
    "resource": "资源",
    "Respec emitters on next sacrifice": "在下一次牺牲时重洗发射器",
    "Respec Ethereal Upgrades": "重洗空灵升级",
    "Respec galaxies - forces ascension": "重洗星系 - 力量提升",
    "Respec galaxies on next ascension": "在下一次提升时重洗星系",
    "Reward: 1 Impossible Theorem.": "奖励：1 个不可能定理。",
    "s: Sacrifice;": "s：牺牲；",
    "Sacrifice": "牺牲",
    "sacrifice your empire": "牺牲你的帝国",
    "sculptor dwarf": "雕塑家矮人",
    "Sculptor Dwarf": "雕刻家矮人",
    "Sculptor Dwarf/Triangulum": "雕刻家矮人/三角座",
    "sec": "秒",
    "seconds, unaffected by astral enslavement or time essence.": "秒，不受星体奴役或时间精华的影响。",
    "Set the world prestige max to 0 for no limit.": "将世界声望最大值设置为 0 无限制。",
    "set to 0 for unlimited": "设置为 0 表示无限制",
    "Shiny Crystals": "闪亮的水晶",
    "single": "单个",
    "SINGLE": "单个",
    "skeleton mages": "骷髅法师",
    "Skeleton Mages": "骷髅法师",
    "SLOW": "慢",
    "Slow autobuyers trigger every 15": "缓慢的自动购买者每 15 次触发一次",
    "softcapped at": "软顶在",
    "speed": "速度",
    "square root of your zombies, rounded down": "僵尸的平方根，向下取整",
    "Square your acolyte gain.": "将你的追随者收益平方。",
    "Star Stasis": "星滞",
    "Start every sacrifice with four exterminated worlds, and the dead sun does not reset on sacrifice.": "以四个被灭绝的世界开始每个牺牲，死日不会在牺牲时重置。",
    "Start every sacrifice with one exterminated world, and Buildings and Behemoths unlocked.": "从一个灭​​绝的世界开始每一次牺牲，并解锁建筑物和巨兽。",
    "Start every sacrifice with one free exterminated world that doesn't increase the world prestige requirement.": "以一个不会增加世界声望要求的自由灭绝世界开始每一次牺牲。",
    "Start every sacrifice with three exterminated worlds and Sun Eaters unlocked, and unlock autobuyers.": "从三个灭绝的世界和 日蚀者 解锁开始每一次牺牲，并解锁 自动购买者。",
    "Start every sacrifice with two exterminated worlds, and Construction and Ancient Ones unlocked.": "从两个灭绝的世界开始每一次牺牲，并解锁建筑和古人。",
    "STATS": "统计数据",
    "STATS ETC": "统计等",
    "stays active during research.": "在研究期间保持活跃。",
    "Stronger Forges": "更强的锻造",
    "Sun Eaters": "太阳食者",
    "Supernova": "超新星",
    "t: Respec Time Production;": "t：重洗时间生产；",
    "Thanks to hevipelle and jacorb for making their games (and making their code open) and thanks to patashu for": "感谢 hevipelle 和 jacorb 制作他们的游戏（并开放他们的代码），感谢 patashu",
    "Thanks toughtoffee for the awesome logo/favicon.": "感谢toughtoffee 提供了令人敬畏的徽标/网站图标。",
    "The": "这",
    "the Anti Time effect by": "反时间效应",
    "The anti time effect is equal to the true time effect whenever it would be 1x.": "只要反时间效应为 1x，反时间效应就等于真正的时间效应。",
    "The anti time essence effect is disabled.": "反时间精华效果被禁用。",
    "The Astral Brick Road": "星体砖路",
    "The astral time nerf doesn't apply to nekro-photon production (but you still only produce them during astral).": "星界时间 nerf 不适用于 nekro-photon 生产（但你仍然只在星界期间生产它们）。",
    "The base zombie corpse multiplier is increased, 1.75 -> 2.5.": "基础僵尸尸体乘数增加，1.75 -> 2.5。",
    "the beyond": "超越",
    "The Beyond holds infinite, untold knowledge.": "彼岸拥有无穷无尽的知识。",
    "The corpse production multiplier from exterminated worlds is 1.5x stronger.": "灭绝世界的尸体生产乘数要强 1.5 倍。",
    "The Death Factory is disabled.": "死亡工厂被禁用。",
    "The Death Factory's first upgrade row is never reset.": "死亡工厂的第一个升级行永远不会重置。",
    "The effect of each second row Necropolis upgrade directly applies to the effect of the upgrade above it.": "第二排墓地升级的效果直接适用于其上方升级的效果。",
    "The effects of the first four construction upgrades are each 20% stronger.": "前四次建筑升级的效果各强 20%。",
    "The first three building resources get a production boost based on unspent time crystals.": "前三个建筑资源基于未使用的时间水晶获得产量提升。",
    "The first time upgrade in the fourth and fifth columns stay active during research.": "第四列和第五列的第一次升级在研究期间保持活跃。",
    "The Prestige Tree": "声望树",
    "The sacrifice threshold and crystal gain formula are based on 1e20 -> 1e15 corpses.": "牺牲阈值和水晶增益公式是基于1e20 -> 1e15 尸体。",
    "The square root of your total galaxies multiplies both time boosts.": "你的星系总数的平方根乘以两个时间提升。",
    "the True Time effect by": "真实时间效应",
    "The two additional columns of upgrades from milestone 6 are never reset.": "里程碑 6 的另外两列升级永远不会重置。",
    "There must be loss in exchange for true power.": "必须有损失才能换取真正的力量。",
    "This game was made by monkeh42, and is very heavily influenced by hevipelle's": "此游戏由monkeh42 制作，深受hevipelle 的影响",
    "this many": "自定义数量",
    "This world is dead and empty...": "这个世界是死的，是空的……",
    "This world prestige will unlock the Refinery and a new unit tier.": "这个世界声望将解锁炼油厂和一个新的单位等级。",
    "Thyme Lord": "百里香领主",
    "Tier": "等级",
    "TIME": "时间",
    "TIME DISPLAYS: GAME TIME": "时间显示：游戏时间",
    "Time Emitters": "时间发射器",
    "time is going": "时间过去了",
    "To complete a research project, you must reach the required amount of Void Research under these conditions in addition to the specific conditions below.": "要完成一项研究项目，除了以下特定条件外，您还必须在这些条件下达到所需的虚空研究数量。",
    "Toggle All Amount": "切换所有金额",
    "toggle all autobuyers": "切换所有自动购买者",
    "Toggle All On/Off": "切换所有开/关",
    "Toggle All Speed": "切换所有速度",
    "TOGGLE CONFIRMATIONS": "切换确认",
    "toggle unit autobuyers": "切换单元自动购买者",
    "total": "全部的",
    "Total corpse gain multiplier from all sources": "所有来源的总尸体增益乘数",
    "Total corpse gain multiplier from units": "单位的总尸体增益乘数",
    "total formed.": "总形成。",
    "triangulum": "三角座",
    "Triangulum": "三角座",
    "TRUE": "真实",
    "True and anti time emitters no longer nerf the other's effect.": "真实和反时间发射器不再削弱对方的效果。",
    "True Time Emitters": "真正的时间发射器",
    "true time essence and": "真正的时间精华和",
    "Full Stasis": "完全静止",
    "g: Respec Galaxies;": "g：重洗星系；",
    "gain": "获得",
    "Gain": "获得",
    "Gain 20% more astral bricks for each OoM (order of magnitude) of astral bricks owned.": "每拥有一个 OoM（数量级）的星体砖，就可以多获得 20% 的星体砖。",
    "Galactic Vortex and the 4th/5th Time Upgrade columns don't reset, but they have no effect during research.": "银河漩涡和第 4 次/第 5 次升级栏不会重置，但它们在研究期间没有效果。",
    "galaxies": "星系",
    "Galaxy Milestones": "银河里程碑",
    "galaxy tree is locked.": "银河树被锁定。",
    "Game Autosaved!": "游戏自动保存！",
    "Give up all your units and corpses to exterminate a new world. You get a boost to corpse production based on total exterminated worlds.": "放弃你所有的单位和尸体来消灭一个新的世界。您可以根据已灭绝的世界总数来提高尸体生产。",
    "Goal": "目标",
    "HELP": "帮助",
    "HELP (full text": "帮助（全文",
    "here!": "这里！",
    "hotkeys": "热键",
    "hotkeys do not trigger if ctrl or command (mac) is pressed.": "如果按下 ctrl 或命令 (mac)，则不会触发热键。",
    "Hypertime": "超时",
    "if you see this for more than a few seconds, something's wrong. please contact the dev on": "如果您看到此内容超过几秒钟，则说明有问题。请联系开发人员",
    "IMPORT": "进口",
    "Import Galaxies": "导入星系",
    "IMPORT SAVE": "导入保存",
    "impossible theorem": "不可能定理",
    "Increase refinery level": "提高炼油厂等级",
    "Increase the base corpse multiplier of unit tiers 2 through 8 by 25%.": "将单位层 2 到 8 的基础尸体乘数提高 25%。",
    "Increase the exponent on the astral brick production formula from ^0.2 -> ^0.3.": "将星界砖生产公式的指数从 ^0.2 -> ^0.3 增加。",
    "Increases the base corpse multiplier of zombies by 5% per level.": "每级增加 5% 的僵尸基础尸体乘数。",
    "Industrialize": "工业化",
    "Infinite Research": "无限研究",
    "Infinite research is the same as research project 6, with corpse production raised ^0.9 a second time. Infinite research can be completed unlimited times: each completion raises time crystal gain to ^1.01, and multiplies the goal amount by 10.": "无限研究与研究项目6相同，尸体产量第二次提高^0.9。无限研究可无限次完成：每次完成将时间水晶增益提升至^1.01，目标数量乘以10。",
    "infinite research projects": "无限的研究项目",
    "Inter-Dimensional Nekro-Cable": "跨维度 Nekro 电缆",
    "invalid entry. amount set to last good value: {{ player.emittersAmount }}": "输入无效。金额设置为最后一个好值：{{ player.emittersAmount }}",
    "It's About Time": "是时候了",
    "Killing Time": "消磨时间",
    "Last 10 Ascension Runs": "最近 10 次提升运行",
    "Last 10 Sacrifice Runs": "最近 10 次牺牲运行",
    "liches": "巫妖",
    "Liches": "巫妖",
    "Lightspeed": "光速",
    "Load/Save Favorites": "加载/保存收藏夹",
    "Lock in and begin time production": "锁定并开始时间制作",
    "m: Max All Units;": "m：最大所有单位；",
    "MANUAL LOAD": "手动加载",
    "MANUAL SAVE": "手动保存",
    "Master Of The Dead": "亡灵大师",
    "Max all": "全部最大",
    "max auto prestiges": "最大自动声望",
    "Meta-Solar": "元太阳能",
    "Militarize": "军事化",
    "MORE...CORPSES...": "更多...尸体...",
    "n: Ascension;": "n：提升；",
    "necropolis": "墓地",
    "Nekro-Carpentry": "死灵木工",
    "nekro-photons.": "死光子。",
    "NORMAL": "普通的",
    "NOTE": "笔记",
    "Nothing.": "没有。",
    "Number Keys 1-8: Buy Single Unit; shift+(1-8): Buy Max Units;": "数字键 1-8：购买单件； shift+(1-8)：购买最大单位；",
    "Of course, you have undead souls to do your studying for you.": "当然，你有不死的灵魂为你学习。",
    "of your astral bricks, buildings, upgrades, and time crystals are reset, and you start with 10 corpses. All tabs stay unlocked.": "你的星体砖、建筑、升级和时间水晶被重置，你从 10 具尸体开始。所有标签保持解锁状态。",
    "Offline Production": "线下生产",
    "on sacrifice.": "关于牺牲。",
    "on/off": "开关",
    "Once unlocked, the prestige buyer and the fast, bulk, and advanced upgrades are permanently available whenever autobuyers are.": "一旦解锁，声望购买者和快速、批量和高级升级将在自动购买者出现时永久可用。",
    "One Sun, Two Sun, Dead Sun, Blue Sun": "一个太阳，两个太阳，死太阳，蓝色太阳",
    "OPTIONS": "选项",
    "or": "或",
    "out of": "超出",
    "Owned": "拥有",
    "p: World Prestige;": "p：世界声望；",
    "Paste your save here...": "在此处粘贴您的保存...",
    "Perform a dark ritual to transmute all you have achieved into time crystals. This will reset all your corpses, units, worlds, bricks, buildings, and building upgrades, but you will gain time crystals based on your corpses.": "执行一个黑暗的仪式，将你所取得的一切转化为时间水晶。这将重置你所有的尸体、单位、世界、砖块、建筑和建筑升级，但你会根据你的尸体获得时间水晶。",
    "performing an ascension or galaxy respec will exit the current project and set your void research to 0.": "执行提升或星系重新规范将退出当前项目并将你的虚空研究设置为 0。",
    "Practical Theoretics": "实用理论",
    "Priority": "优先",
    "production other than astral bricks and void research is raised to ^0.9.": "星界砖和虚空研究以外的产量提高到 ^0.9。",
    "q: Units Tab;": "q：单位选项卡；",
    "Quadruple your time crystal gain.": "使您的时间水晶增益翻两番。",
    "Quantum Equivalence": "量子等价",
    "r: Galaxies Tab;": "r：星系标签；",
    "Rapid Fire": "熊熊大火",
    "real time": "即时的",
    "real-world": "真实世界",
    "armaments.": "军备。",
    "ASCENSION": "扬升",
    "ascensions": "提升",
    "Assign Emitters": "分配发射器",
    "ASTRAL": "星界",
    "astral bricks\n": "星体砖\n",
    "Astral Bricks and": "星界砖块和",
    "astral bricks.": "星体砖。",
    "ASTRAL ENSLAVEMENT": "星体奴役",
    "Astral Forges": "星界熔炉",
    "Astral Kilns": "星界窑",
    "Astral Siege Engines": "星界攻城引擎",
    "at a time": "一次",
    "at x crystals": "在 x 晶体",
    "at x times last": "最后 x 次",
    "banshees": "女妖",
    "Banshees": "女妖",
    "BEGIN": "开始",
    "behemoths": "巨兽",
    "Behemoths": "巨兽",
    "best": "最好的",
    "Boost armament production based on astral bricks.": "提高基于星体砖的武器生产。",
    "Boost corpse production based on astral bricks.": "基于星界砖提高尸体生产。",
    "Boosts the abomination unit multiplier by 10% per level.": "每级提高憎恶单位乘数 10%。",
    "Bought": "已购买",
    "break_infinity.js": "break_infinity.js",
    "bricks": "砖块",
    "Building Boost": "建设提升",
    "building resources,": "建设资源，",
    "BUILDINGS": "建筑",
    "but not built buildings or purchased upgrades.": "但没有建造建筑物或购买升级。",
    "but they divide": "但他们除以",
    "Buy max": "购买最大",
    "Buying a 4th row upgrade will increase the cost of the 1st row upgrades by 1.": "购买第 4 排升级将使第 1 排升级的成本增加 1。",
    "Calculating offline production...": "计算离线生产...",
    "CHANGELOG": "变更日志",
    "Check out my other projects": "查看我的其他项目",
    "circinus": "圆环",
    "Circinus": "圆环",
    "CLOSE": "关闭",
    "completed achievement rows, giving a": "完成的成就行，给出一个",
    "completed rows": "完成的行",
    "Completing a project respecs galaxies without an ascension reset.": "完成一个项目重洗星系，而无需重新设置提升。",
    "condition": "健康）状况",
    "congratulations. you have gone beyond.": "祝贺。你已经超越了。",
    "CONSTRUCTION": "构造",
    "CONSTRUCTION UPGRADES": "建筑升级",
    "continue your domination?": "继续你的统治？",
    "Corpse Mult": "尸体乘数",
    "Corpse production disabled due to Astral Enslavement.": "由于星界奴役，尸体生产被禁用。",
    "Corpse production is raised to the ^0.9 a second time.": "尸体产量第二次提高到 ^0.9。",
    "corpses": "尸体",
    "corpses.": "尸体。",
    "Cube the": "立方体",
    "CUSTOMIZE HEADER": "自定义标题",
    "dead sun": "死日",
    "death factory": "死亡工厂",
    "Decrease the astral enslavement time nerf even more, 5x -> 2x.": "进一步减少星体奴役时间，5x -> 2x。",
    "Decrease the astral enslavement time nerf from 10x -> 5x.": "将星体奴役时间从 10 倍降低到 5 倍。",
    "depleted galaxies": "耗尽的星系",
    "depleted galaxies.": "耗尽的星系。",
    "depleted galaxy, but when you buy one, all others on rows below it increase in cost by 1.": "耗尽的星系，但是当您购买一个时，其下方行中的所有其他星系的成本都会增加 1。",
    "Digitize": "数字化",
    "DISCORD": "不和谐",
    "Display": "展示",
    "Don't unlock time on ascension": "不要在提升时解锁时间",
    "Double your time crystal gain.": "双倍的时间水晶增益。",
    "During astral enslavement, your vassal souls tirelessly study the eldritch sciences of": "在星界奴役期间，你的附庸灵魂不知疲倦地研究",
    "e: Time Tab;": "e：时间标签；",
    "Each Ark component built multiplies corpse production by 10.": "每建造一个方舟组件，尸体产量就会增加 10 倍。",
    "Each project completed doubles the number of galaxies the galaxy softcaps start at.": "每个完成的项目都会使星系软帽开始的星系数量翻倍。",
    "Each unit tier produces the tier below it at a rate of 1/unit/sec instead of (1/tier)/unit/sec.": "每个单位层以 1/单位/秒而不是 (1/层)/单位/秒的速率产生低于它的层。",
    "Each unit tier's base unit multiplier is equal to its corpse multiplier, instead of the square root.": "每个单位层的基本单位乘数等于其尸体乘数，而不是平方根。",
    "effect squared also applies to the production of corpses and astral bricks.": "效果平方也适用于尸体和星界砖的生产。",
    "effect.": "影响。",
    "Effects that apply to \"corpse production\" don't affect this.": "适用于“尸体生产”的效果不会影响这一点。",
    "ENABLE HOTKEYS: ON": "启用热键：开",
    "Ethereal Upgrades": "空灵升级",
    "Even in your godlike state this is beyond you. This will require study.": "即使在你神一样的状态下，这也超出了你的范围。这将需要研究。",
    "Even-numbered refinery levels give one additional emitter.": "偶数炼油厂级别提供了一个额外的发射器。",
    "Every completion rewards 1 Impossible Theorem. Each unspent theorem raises the exterminated worlds effect to ^1.2, and they are used to buy Ethereal Upgrades.": "每次完成都会奖励 1 个不可能定理。每个未使用的定理都会将灭绝世界效应提高到 ^1.2，并且它们用于购买虚灵升级。",
    "Exp. cost scaling for all construction upgrades starts 10 levels later (after 3.22).": "经验。所有建筑升级的成本缩放在 10 个级别后开始（3.22 之后）。",
    "Exponential cost scaling for all construction upgrades starts at level 1.": "所有建筑升级的指数成本缩放从级别 1 开始。",
    "Exponential cost scaling for all units starts after twice as many bought.": "所有单位的指数成本缩放在购买数量增加一倍后开始。",
    "Exponential cost scaling for the first four construction upgrades starts after twice as many levels.": "前四个建筑升级的指数成本缩放在两倍的级别之后开始。",
    "Export Galaxies": "导出星系",
    "EXPORT SAVE": "出口保存",
    "exterminated worlds": "灭绝的世界",
    "f: Cycle Subtabs;": "f：循环子选项卡；",
    "Factory Expansion": "工厂扩建",
    "forces a sacrifice reset": "强制牺牲重置",
    "Forgotten Worlds": "被遗忘的世界",
    "FORMULA TOOLTIPS: OFF": "公式工具提示：关闭",
    " at a time": " 一次",
    " congratulations. you have gone beyond.": "祝贺。你已经超越了。",
    " continue your domination?": " 继续你的统治？",
    " if you see this for more than a few seconds, something's wrong. please contact the dev on": " 如果您看到此内容超过几秒钟，则说明有问题。请联系开发人员",
    " You gained": " 你获得了",
    ", and similar games.": "，以及类似的游戏。",
    ", boosting all units' corpse multipliers by": ", 将所有单位的尸体乘数提高",
    ", giving a": "，给出一个",
    ", jacorb's": ", 雅各布的",
    ", raising the exterminated worlds effect to ^": ", 将灭绝世界效应提升到 ^",
    ", raising time crystal gain to ^": ", 提高时间晶体增益到 ^",
    ". As a result, your base astral brick production is square rooted, but you produce Void Research at the same base rate.": ".结果，您的基础星体砖产量是平方根，但您以相同的基础速率生产虚空研究。",
    "\"Make yourself an ark of astral matter; make rooms in the ark, and cover it inside and outside with time.\"": "“让你自己成为一个星光物质的方舟；在方舟中建造房间，并用时间覆盖它的内外。”",
    "\"We have found you worthy of our ranks, small one.\"": "“我们发现你配得上我们的队伍，小个子。”",
    "(based on your bought sun eaters": "（基于您购买的日蚀者",
    "(based on your zombies": "（基于你的僵尸",
    "(softcapped at": "（软顶在",
    "A galaxy respec resets all costs to 1, and unlocks all locked upgrades.": "星系重洗 将所有成本重置为 1，并解锁所有锁定的升级。",
    "a: Toggle Astral Enslavement;": "a：切换星体奴役；",
    "Abominable Steroids": "可恶的类固醇",
    "abominations": "憎恶",
    "Abominations": "憎恶",
    "achievements": "成就",
    "ACHIEVEMENTS": "成就",
    "achievements and": "成就和",
    "Achievements with a '+' have an additional reward; hover to view requirements and rewards.": "带“+”的成就有额外奖励；悬停查看要求和奖励。",
    "acolytes": "追随者",
    "acolytes.": "追随者。",
    "Add .02 per level to the armament gain exponent.": "武器增益指数每增加 0.02。",
    "Add .02 per level to the exponent of the exterminated worlds boost to corpse gain.": "每级增加 0.02 到灭绝世界的指数增加尸体增益。",
    "Additionally, galaxy upgrade costs are tripled (after the cost increase from higher rows), and": "此外，星系升级成本增加了三倍（在更高行的成本增加之后），并且",
    "after x seconds": "x 秒后",
    "All effects based on total galaxies are softcapped at": "基于总星系的所有影响都被软封顶",
    "All galaxy upgrades have a base cost of": "所有星系升级的基本成本为",
    "All Time": "整天",
    "All unit tier corpse multipliers are raised to the ^0.9.": "所有单位层的尸体乘数都提高到 ^0.9。",
    "All unit tier corpse multipliers are raised to the ^1.1.": "所有单位层的尸体乘数都提高到 ^1.1。",
    "amount": "数量",
    "ancient ones": "古人",
    "Ancient Ones": "古人",
    "and": "和",
    "and contains": "并包含",
    "and they multiply": "他们成倍增加",
    "andromeda": "仙女座",
    "Andromeda": "仙女座",
    "Andromeda/Circinus": "仙女座/圆环",
    "ANTI": "反",
    "Anti Time Emitters": "反时间发射器",
    "anti time essence.": "反时间本质。",
    "Antimatter Dimensions": "反物质维度",
    "Arm your zombies, giving a boost to their corpse multiplier based on armaments.": "武装你的僵尸，以武器为基础提高他们的尸体乘数。",
    "armaments": "军备",
    "Build the": "建造",
    "disable": "点击禁用",
    "you have": "你有 ",
    "enable": "点击启用",
    "Achievement Unlocked!": "成就已达成！",
    "Are You Sure?": "你确定吗？",
    "CLOSE HELP": "关闭帮助",
    "corpse": "尸体",
    "LAST 10 SAC.": "最近 10 牺牲",
    "NO": "否",
    "REFINERY": "炼油厂",
    "Respec emitters - forces sacrifice": "重洗发射器 - 强制牺牲",
    "These confirmations can be disabled in options": "这些确认可以在选项中禁用",
    "This will reset ALL of your corpses, units, and astral bricks.": "这将重置你所有的尸体、单位和星界砖。",
    "This will reset ALL of your progress before unlocking Time Warp, and all of your time essense.": "这将在解锁时间扭曲之前重置您的所有进度，以及您所有的时间本质。",
    "YES": "是的",
    "armament": "军备",
    "astral brick": "星体砖",
    "Requires 1 sun eater": "需要1个日蚀者",
    "Anti Time Emitter": "反时间发射器",
    "This Sacrifice": "这个牺牲",
    "This world prestige will unlock Buildings and a new unit tier.": "这种世界声望将解锁建筑物和新的单位等级。",
    "Time Emitter": "时间发射器",
    "This world prestige will unlock Construction and a new unit tier.": "这个世界声望将解锁建筑和新的单位等级。",
    "Requires 1 behemoth": "需要1个巨兽",
    "world": "世界",
    "Requires 1 ancient one": "需要 1 个古人",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'DISCORD': 'DISCORD',
    'discord': 'discord',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t\t": "\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "World Stasis ": "世界停滞 ",
    "Project ": "项目 ",
    "Buy max (": "购买最大 (",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "time crystals": "时间水晶",
    "astral bricks": "星体砖",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Avg. of past 10 runs: (.+); (.+) crystals; (.+) crystals\/min$/, '平均过去 10 次游戏时长：$1； $2 水晶； $3 水晶/分钟'],
    [/^(.+) crystals; (.+) crystals\/min$/, '$1 水晶； $2 水晶\/分钟'],
    [/^your best crystal gain was (.+) and your best crystal gain rate was (.+)\/min$/, '您的最佳水晶增益为 $1，您的最佳水晶增益率为 $2\/分钟'],
    [/^you have world prestiged (.+) times$/, '你世界声望了 $1 次'],
	[/^\/ ascended (.+) times$/, '\/ 转生了 $1 次'],
	[/^\/ sacrificed (.+) times$/, '\/ 牺牲了 $1 次'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) exterminated world$/, '$1 灭绝的世界'],
	[/^([\d\.,]+) armaments$/, '$1 军备'],
	[/^([\d\.,]+) corpses$/, '$1 尸体'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) impossible theorem$/, '$1 不可能定理'],
	[/^([\d\.]+) galaxy$/, '$1 星系'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+)e([\d\.,]+) corpses$/, '$1e$2 尸体'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Goal: (.+) Void Research$/, '目标：$1 虚空研究'],
    [/^Current Goal: (.+) Void Research$/, '当前目标：$1 虚空研究'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Level: (\d+)$/, '等级：$1'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);