/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "worlds": "世界",
    "You can now force the dead you harvest to work for your rapidly growing empire. While Astral Enslavement is active, time goes 10x slower,\n                                and you won't gain any corpses; instead, those tortured, miasmic souls will suffer tirelessly making bricks for your most unholy of foundations.": "你现在可以强迫你收获的死者为你快速发展的帝国工作。 当星体奴役激活时，时间会慢 10 倍，\n 你不会得到任何尸体； 相反，那些饱受折磨的瘴气灵魂将不知疲倦地为你最邪恶的地基砌砖。",
    "Cost: {{ formatUR(getRefineryCost(), 0) }} ": "成本: {{ formatUR(getRefineryCost(), 0) }} ",
    ". (@ {{ getAstralNerf() }}x slower time speed": ". (@ {{ getAstralNerf() }}x 更慢的时间速度",
    "You will gain {{ formatWhole(getEmittersPerLevel()) }} additional emitters.": "你将获得 {{ formatWhole(getEmittersPerLevel()) }} 额外发射器.",
    "Turn All Off": "全部关闭",
    "Turn All On": "全部开启",
    "Ultra-Solar": "超太阳能",
    "unassigned emitters.": "未分配的发射器。",
    "Unit autobuyers attempt to buy in order from priority 1 to priority 8.": "单位自动购买者尝试按照优先级 1 到优先级 8 的顺序购买。",
    "Unit Boost": "单位提升",
    "Unit Mult": "单位乘数",
    "Unit tier corpse multipliers get a boost based on unspent time crystals.": "单位层尸体乘数会根据未使用的时间水晶获得提升。",
    "Unit Type": "单位类型",
    "UNITS": "单位",
    "UNLEASH DEATH": "释放死亡",
    "Unlock bulk autobuyers permanently, and crystal gain is boosted based on your nekro-photons.": "永久解锁大宗自动购买者，水晶增益会根据你的 nekro-photons 得到提升。",
    "Unlock fast autobuyers permanently, and the buildings/construction tabs are never reset on sacrifice (except bricks and resources).": "永久解锁快速自动购买者，并且建筑物/建筑标签永远不会因牺牲而重置（砖块和资源除外）。",
    "Unlock the second row of Dead Sun upgrades, and increase base emitters gained per refinery level from 1 -> 2.": "解锁第二排死日升级，每精炼厂等级获得的基础发射器从 1 -> 2 增加。",
    "Unlock the second row of Galactic Vortex upgrades.": "解锁第二排银河漩涡升级。",
    "Unlock the world prestige autobuyer permanently.": "永久解锁世界声望自动购买者。",
    "Void Research production is multiplied by the log of your current bricks/sec.": "虚空研究产量乘以您当前砖块/秒的日志。",
    "void research.": "无效的研究。",
    "w: Buildings Tab;": "w：建筑物选项卡；",
    "When you begin a research project, you do a galaxy respec and time respec,": "当你开始一个研究项目时，你会做一个银河系和时间方面的研究，",
    "without any exceptons from milestones, achievements past the first row, or project rewards": "里程碑、超过第一行的成就或项目奖励没有任何例外",
    "World Prestige": "世界声望",
    "World Prestige resets your": "世界声望重置你的",
    "World Refiner": "世界精炼者",
    "x as fast.": "x 一样快。",
    "x bonus to corpse gain.": "x 尸体增益加成。",
    "x slower time speed": "x 较慢的时间速度",
    "You are gaining": "你正在获得",
    "You are harvesting": "你在收获",
    "you are producing": "你正在生产",
    "You are producing": "你在生产",
    "You can only buy one galaxy upgrade from each tree and from each row (the normal upgrade requirements are suspended).": "您只能从每棵树和每行购买一个星系升级（暂停正常升级要求）。",
    "You can only buy one galaxy upgrade from each tree and from each row.": "您只能从每棵树和每一行购买一个星系升级。",
    "You can only use one galaxy tree.": "您只能使用一棵星系树。",
    "You can't take both branches in the same tree; buying an upgrade in the 2nd row will lock out the two in the other branch.": "你不能在同一棵树上取两个分支；在第二排购买升级将锁定另一个分支中的两个。",
    "you don't have any past runs!": "您没有任何过去的跑步记录！",
    "You gained": "你获得了",
    "You have achieved": "你已经达到",
    "You have completed": "您已完成",
    "You have exterminated": "你已经消灭了",
    "You have formed": "你已经形成",
    "YOU HAVE GONE BEYOND.": "你已经超越了。",
    "You have the knowledge needed to craft The Ark, but your thirst has not been quenched.": "你拥有制作方舟所需的知识，但你的渴望并没有被解渴。",
    "You produce 1% of your corpse production while in astral enslavement.": "在星界奴役期间，你生产 1% 的尸体。",
    "You produce your astral brick production ^0.9 outside of astral enslavement (still affected by the astral time nerf).": "你在星界奴役之外生产你的星界砖生产^0.9（仍然受到星界时间削弱的影响）。",
    "You receive a message from beyond.": "你收到来自彼岸的消息。",
    "You will keep": "你会保持",
    "Your": "您的",
    "Your achievements and achievement rewards are permanent. They persist through": "您的成就和成就奖励是永久的。他们坚持通过",
    "your acolytes chant into the astral abyss, boosting your astral brick gain by": "你的追随者向星界深渊吟唱，提高你的星界砖增益",
    "Your Anti Time Emitters speed up astral time by": "你的反时间发射器加速星光时间",
    "Your Refinery is level": "你的精炼厂等级是",
    "Your refinery level multiplies the anti time effect.": "你的精炼厂等级乘以反时间效果。",
    "Your refinery level multiplies the true time effect.": "您的精炼厂级别会乘以真实的时间效果。",
    "Your total galaxies multiply unit production multipliers.": "你的星系总数乘以单位生产乘数。",
    "Your True Time Emitters speed up normal time by": "您的真实时间发射器将正常时间加快",
    "Your unholy hordes have forged": "你的邪恶部落已经锻造",
    "zombies": "僵尸",
    "Zombies": "僵尸",
    "Zombies also produce Sun Eaters at a very greatly reduced rate (sqrt(log)).": "僵尸也以非常低的速率（sqrt（log））产生日蚀者。",
    "Recrystallization": "重结晶",
    "Refinery Efficiency": "精炼厂效率",
    "Requires": "需要",
    "Requires at least 10 exterminated worlds": "需要至少 10 个已灭绝的世界",
    "Requires at least 1e20 corpses": "需要至少 1e20 具尸体",
    "Reset for": "重置为",
    "resets.": "重置。",
    "resource": "资源",
    "Respec emitters on next sacrifice": "在下一次牺牲时重洗发射器",
    "Respec Ethereal Upgrades": "重洗空灵升级",
    "Respec galaxies - forces ascension": "重洗星系 - 力量提升",
    "Respec galaxies on next ascension": "在下一次提升时重洗星系",
    "Reward: 1 Impossible Theorem.": "奖励：1 个不可能定理。",
    "s: Sacrifice;": "s：牺牲；",
    "Sacrifice": "牺牲",
    "sacrifice your empire": "牺牲你的帝国",
    "sculptor dwarf": "雕塑家矮人",
    "Sculptor Dwarf": "雕刻家矮人",
    "Sculptor Dwarf/Triangulum": "雕刻家矮人/三角座",
    "sec": "秒",
    "seconds, unaffected by astral enslavement or time essence.": "秒，不受星体奴役或时间精华的影响。",
    "Set the world prestige max to 0 for no limit.": "将世界声望最大值设置为 0 无限制。",
    "set to 0 for unlimited": "设置为 0 表示无限制",
    "Shiny Crystals": "闪亮的水晶",
    "single": "单个",
    "SINGLE": "单个",
    "skeleton mages": "骷髅法师",
    "Skeleton Mages": "骷髅法师",
    "SLOW": "慢",
    "Slow autobuyers trigger every 15": "缓慢的自动购买者每 15 次触发一次",
    "softcapped at": "软顶在",
    "speed": "速度",
    "square root of your zombies, rounded down": "僵尸的平方根，向下取整",
    "Square your acolyte gain.": "将你的追随者收益平方。",
    "Star Stasis": "星滞",
    "Start every sacrifice with four exterminated worlds, and the dead sun does not reset on sacrifice.": "以四个被灭绝的世界开始每个牺牲，死日不会在牺牲时重置。",
    "Start every sacrifice with one exterminated world, and Buildings and Behemoths unlocked.": "从一个灭​​绝的世界开始每一次牺牲，并解锁建筑物和巨兽。",
    "Start every sacrifice with one free exterminated world that doesn't increase the world prestige requirement.": "以一个不会增加世界声望要求的自由灭绝世界开始每一次牺牲。",
    "Start every sacrifice with three exterminated worlds and Sun Eaters unlocked, and unlock autobuyers.": "从三个灭绝的世界和 日蚀者 解锁开始每一次牺牲，并解锁 自动购买者。",
    "Start every sacrifice with two exterminated worlds, and Construction and Ancient Ones unlocked.": "从两个灭绝的世界开始每一次牺牲，并解锁建筑和古人。",
    "STATS": "统计数据",
    "STATS ETC": "统计等",
    "stays active during research.": "在研究期间保持活跃。",
    "Stronger Forges": "更强的锻造",
    "Sun Eaters": "日蚀者",
    "Supernova": "超新星",
    "t: Respec Time Production;": "t：重洗时间生产；",
    "Thanks to hevipelle and jacorb for making their games (and making their code open) and thanks to patashu for": "感谢 hevipelle 和 jacorb 制作他们的游戏（并开放他们的代码），感谢 patashu",
    "Thanks toughtoffee for the awesome logo/favicon.": "感谢toughtoffee 提供了令人敬畏的徽标/网站图标。",
    "The": "这",
    "the Anti Time effect by": "反时间效应",
    "The anti time effect is equal to the true time effect whenever it would be 1x.": "只要反时间效应为 1x，反时间效应就等于真正的时间效应。",
    "The anti time essence effect is disabled.": "反时间精华效果被禁用。",
    "The Astral Brick Road": "星体砖路",
    "The astral time nerf doesn't apply to nekro-photon production (but you still only produce them during astral).": "星界时间 nerf 不适用于 nekro-photon 生产（但你仍然只在星界期间生产它们）。",
    "The base zombie corpse multiplier is increased, 1.75 -> 2.5.": "基础僵尸尸体乘数增加，1.75 -> 2.5。",
    "the beyond": "超越",
    "The Beyond holds infinite, untold knowledge.": "彼岸拥有无穷无尽的知识。",
    "The corpse production multiplier from exterminated worlds is 1.5x stronger.": "灭绝世界的尸体生产乘数要强 1.5 倍。",
    "The Death Factory is disabled.": "死亡工厂被禁用。",
    "The Death Factory's first upgrade row is never reset.": "死亡工厂的第一个升级行永远不会重置。",
    "The effect of each second row Necropolis upgrade directly applies to the effect of the upgrade above it.": "第二排墓地升级的效果直接适用于其上方升级的效果。",
    "The effects of the first four construction upgrades are each 20% stronger.": "前四次建筑升级的效果各强 20%。",
    "The first three building resources get a production boost based on unspent time crystals.": "前三个建筑资源基于未使用的时间水晶获得产量提升。",
    "The first time upgrade in the fourth and fifth columns stay active during research.": "第四列和第五列的第一次升级在研究期间保持活跃。",
    "The Prestige Tree": "声望树",
    "The sacrifice threshold and crystal gain formula are based on 1e20 -> 1e15 corpses.": "牺牲阈值和水晶增益公式是基于1e20 -> 1e15 尸体。",
    "The square root of your total galaxies multiplies both time boosts.": "你的星系总数的平方根乘以两个时间提升。",
    "the True Time effect by": "真实时间效应",
    "The two additional columns of upgrades from milestone 6 are never reset.": "里程碑 6 的另外两列升级永远不会重置。",
    "There must be loss in exchange for true power.": "必须有损失才能换取真正的力量。",
    "This game was made by monkeh42, and is very heavily influenced by hevipelle's": "此游戏由monkeh42 制作，深受hevipelle 的影响",
    "this many": "自定义数量",
    "This world is dead and empty...": "这个世界是死的，是空的……",
    "This world prestige will unlock the Refinery and a new unit tier.": "这个世界声望将解锁精炼厂和一个新的单位等级。",
    "Thyme Lord": "百里香领主",
    "Tier": "等级",
    "TIME": "时间",
    "TIME DISPLAYS: GAME TIME": "时间显示：游戏时间",
    "Time Emitters": "时间发射器",
    "time is going": "时间过去了",
    "To complete a research project, you must reach the required amount of Void Research under these conditions in addition to the specific conditions below.": "要完成一项研究项目，除了以下特定条件外，您还必须在这些条件下达到所需的虚空研究数量。",
    "Toggle All Amount": "切换所有数量",
    "toggle all autobuyers": "切换所有自动购买者",
    "Toggle All On/Off": "切换所有开/关",
    "Toggle All Speed": "切换所有速度",
    "TOGGLE CONFIRMATIONS": "切换确认",
    "toggle unit autobuyers": "切换单位自动购买者",
    "total": "全部的",
    "Total corpse gain multiplier from all sources": "所有来源的总尸体增益乘数",
    "Total corpse gain multiplier from units": "单位的总尸体增益乘数",
    "total formed.": "总形成。",
    "triangulum": "三角座",
    "Triangulum": "三角座",
    "TRUE": "真实",
    "True and anti time emitters no longer nerf the other's effect.": "真实和反时间发射器不再削弱对方的效果。",
    "True Time Emitters": "真实时间发射器",
    "true time essence and": "真正的时间精华和",
    "Full Stasis": "完全静止",
    "g: Respec Galaxies;": "g：重洗星系；",
    "gain": "获得",
    "Gain": "获得",
    "Gain 20% more astral bricks for each OoM (order of magnitude) of astral bricks owned.": "每拥有一个 OoM（数量级）的星体砖，就可以多获得 20% 的星体砖。",
    "Galactic Vortex and the 4th/5th Time Upgrade columns don't reset, but they have no effect during research.": "银河漩涡和第 4 次/第 5 次升级栏不会重置，但它们在研究期间没有效果。",
    "galaxies": "星系",
    "Galaxy Milestones": "银河里程碑",
    "galaxy tree is locked.": "银河树被锁定。",
    "Game Autosaved!": "游戏自动保存！",
    "Give up all your units and corpses to exterminate a new world. You get a boost to corpse production based on total exterminated worlds.": "放弃你所有的单位和尸体来消灭一个新的世界。您可以根据已灭绝的世界总数来提高尸体生产。",
    "Goal": "目标",
    "HELP": "帮助",
    "HELP (full text": "帮助（全文",
    "here!": "这里！",
    "hotkeys": "热键",
    "hotkeys do not trigger if ctrl or command (mac) is pressed.": "如果按下 ctrl 或命令 (mac)，则不会触发热键。",
    "Hypertime": "超时",
    "if you see this for more than a few seconds, something's wrong. please contact the dev on": "如果您看到此内容超过几秒钟，则说明有问题。请联系开发人员",
    "IMPORT": "进口",
    "Import Galaxies": "导入星系",
    "IMPORT SAVE": "导入保存",
    "impossible theorem": "不可能定理",
    "Increase refinery level": "提高精炼厂等级",
    "Increase the base corpse multiplier of unit tiers 2 through 8 by 25%.": "将单位层 2 到 8 的基础尸体乘数提高 25%。",
    "Increase the exponent on the astral brick production formula from ^0.2 -> ^0.3.": "将星界砖生产公式的指数从 ^0.2 -> ^0.3 增加。",
    "Increases the base corpse multiplier of zombies by 5% per level.": "每级增加 5% 的僵尸基础尸体乘数。",
    "Industrialize": "工业化",
    "Infinite Research": "无限研究",
    "Infinite research is the same as research project 6, with corpse production raised ^0.9 a second time. Infinite research can be completed unlimited times: each completion raises time crystal gain to ^1.01, and multiplies the goal amount by 10.": "无限研究与研究项目6相同，尸体产量第二次提高^0.9。无限研究可无限次完成：每次完成将时间水晶增益提升至^1.01，目标数量乘以10。",
    "infinite research projects": "无限的研究项目",
    "Inter-Dimensional Nekro-Cable": "跨维度死灵卡弗里",
    "invalid entry. amount set to last good value: {{ player.emittersAmount }}": "输入无效。金额设置为最后一个好值：{{ player.emittersAmount }}",
    "It's About Time": "是时候了",
    "Killing Time": "消磨时间",
    "Last 10 Ascension Runs": "最近 10 次提升运行",
    "Last 10 Sacrifice Runs": "最近 10 次牺牲运行",
    "liches": "巫妖",
    "Liches": "巫妖",
    "Lightspeed": "光速",
    "Load/Save Favorites": "加载/保存收藏夹",
    "Lock in and begin time production": "锁定并开始时间制作",
    "m: Max All Units;": "m：最大所有单位；",
    "MANUAL LOAD": "手动加载",
    "MANUAL SAVE": "手动保存",
    "Master Of The Dead": "亡灵大师",
    "Max all": "全部最大",
    "max auto prestiges": "最大自动声望",
    "Meta-Solar": "元太阳能",
    "Militarize": "军事化",
    "MORE...CORPSES...": "更多...尸体...",
    "n: Ascension;": "n：提升；",
    "necropolis": "墓地",
    "Nekro-Carpentry": "死灵木工",
    "nekro-photons.": "死光子。",
    "NORMAL": "普通的",
    "NOTE": "笔记",
    "Nothing.": "没有。",
    "Number Keys 1-8: Buy Single Unit; shift+(1-8): Buy Max Units;": "数字键 1-8：购买单件； shift+(1-8)：购买最大单位；",
    "Of course, you have undead souls to do your studying for you.": "当然，你有不死的灵魂为你学习。",
    "of your astral bricks, buildings, upgrades, and time crystals are reset, and you start with 10 corpses. All tabs stay unlocked.": "你的星体砖、建筑、升级和时间水晶被重置，你从 10 具尸体开始。所有标签保持解锁状态。",
    "Offline Production": "线下生产",
    "on sacrifice.": "关于牺牲。",
    "on/off": "开关",
    "Once unlocked, the prestige buyer and the fast, bulk, and advanced upgrades are permanently available whenever autobuyers are.": "一旦解锁，声望购买者和快速、批量和高级升级将在自动购买者出现时永久可用。",
    "One Sun, Two Sun, Dead Sun, Blue Sun": "一个太阳，两个太阳，死太阳，蓝色太阳",
    "OPTIONS": "选项",
    "or": "或",
    "out of": "超出",
    "Owned": "拥有",
    "p: World Prestige;": "p：世界声望；",
    "Paste your save here...": "在此处粘贴您的保存...",
    "Perform a dark ritual to transmute all you have achieved into time crystals. This will reset all your corpses, units, worlds, bricks, buildings, and building upgrades, but you will gain time crystals based on your corpses.": "执行一个黑暗的仪式，将你所取得的一切转化为时间水晶。这将重置你所有的尸体、单位、世界、砖块、建筑和建筑升级，但你会根据你的尸体获得时间水晶。",
    "performing an ascension or galaxy respec will exit the current project and set your void research to 0.": "执行提升或星系重新规范将退出当前项目并将你的虚空研究设置为 0。",
    "Practical Theoretics": "实用理论",
    "Priority": "优先",
    "production other than astral bricks and void research is raised to ^0.9.": "星界砖和虚空研究以外的产量提高到 ^0.9。",
    "q: Units Tab;": "q：单位选项卡；",
    "Quadruple your time crystal gain.": "使您的时间水晶增益翻两番。",
    "Quantum Equivalence": "量子等价",
    "r: Galaxies Tab;": "r：星系标签；",
    "Rapid Fire": "熊熊大火",
    "real time": "即时的",
    "real-world": "真实世界",
    "armaments.": "军备。",
    "ASCENSION": "扬升",
    "ascensions": "提升",
    "Assign Emitters": "分配发射器",
    "ASTRAL": "星界",
    "astral bricks\n": "星体砖\n",
    "Astral Bricks and": "星界砖块和",
    "astral bricks.": "星体砖。",
    "ASTRAL ENSLAVEMENT": "星体奴役",
    "Astral Forges": "星界熔炉",
    "Astral Kilns": "星界窑",
    "Astral Siege Engines": "星界攻城引擎",
    "at a time": "一次",
    "at x crystals": "在 x 晶体",
    "at x times last": "最后 x 次",
    "banshees": "女妖",
    "Banshees": "女妖",
    "BEGIN": "开始",
    "behemoths": "巨兽",
    "Behemoths": "巨兽",
    "best": "最好的",
    "Boost armament production based on astral bricks.": "提高基于星体砖的武器生产。",
    "Boost corpse production based on astral bricks.": "基于星界砖提高尸体生产。",
    "Boosts the abomination unit multiplier by 10% per level.": "每级提高憎恶单位乘数 10%。",
    "Bought": "已购买",
    "break_infinity.js": "break_infinity.js",
    "bricks": "砖块",
    "Building Boost": "建设提升",
    "building resources,": "建设资源，",
    "BUILDINGS": "建筑",
    "but not built buildings or purchased upgrades.": "但没有建造建筑物或购买升级。",
    "but they divide": "但他们除以",
    "Buy max": "购买最大",
    "Buying a 4th row upgrade will increase the cost of the 1st row upgrades by 1.": "购买第 4 排升级将使第 1 排升级的成本增加 1。",
    "Calculating offline production...": "计算离线生产...",
    "CHANGELOG": "变更日志",
    "Check out my other projects": "查看我的其他项目",
    "circinus": "圆环",
    "Circinus": "圆环",
    "CLOSE": "关闭",
    "completed achievement rows, giving a": "完成的成就行，给出一个",
    "completed rows": "完成的行",
    "Completing a project respecs galaxies without an ascension reset.": "完成一个项目重洗星系，而无需重新设置提升。",
    "condition": "健康）状况",
    "congratulations. you have gone beyond.": "祝贺。你已经超越了。",
    "CONSTRUCTION": "构造",
    "CONSTRUCTION UPGRADES": "建筑升级",
    "continue your domination?": "继续你的统治？",
    "Corpse Mult": "尸体乘数",
    "Corpse production disabled due to Astral Enslavement.": "由于星界奴役，尸体生产被禁用。",
    "Corpse production is raised to the ^0.9 a second time.": "尸体产量第二次提高到 ^0.9。",
    "corpses": "尸体",
    "corpses.": "尸体。",
    "Cube the": "立方体",
    "CUSTOMIZE HEADER": "自定义标题",
    "dead sun": "死日",
    "death factory": "死亡工厂",
    "Decrease the astral enslavement time nerf even more, 5x -> 2x.": "进一步减少星体奴役时间，5x -> 2x。",
    "Decrease the astral enslavement time nerf from 10x -> 5x.": "将星体奴役时间从 10 倍降低到 5 倍。",
    "depleted galaxies": "耗尽的星系",
    "depleted galaxies.": "耗尽的星系。",
    "depleted galaxy, but when you buy one, all others on rows below it increase in cost by 1.": "耗尽的星系，但是当您购买一个时，其下方行中的所有其他星系的成本都会增加 1。",
    "Digitize": "数字化",
    "DISCORD": "不和谐",
    "Display": "展示",
    "Don't unlock time on ascension": "不要在提升时解锁时间",
    "Double your time crystal gain.": "双倍的时间水晶增益。",
    "During astral enslavement, your vassal souls tirelessly study the eldritch sciences of": "在星界奴役期间，你的附庸灵魂不知疲倦地研究",
    "e: Time Tab;": "e：时间标签；",
    "Each Ark component built multiplies corpse production by 10.": "每建造一个方舟组件，尸体产量就会增加 10 倍。",
    "Each project completed doubles the number of galaxies the galaxy softcaps start at.": "每个完成的项目都会使星系软帽开始的星系数量翻倍。",
    "Each unit tier produces the tier below it at a rate of 1/unit/sec instead of (1/tier)/unit/sec.": "每个单位层以 1/单位/秒而不是 (1/层)/单位/秒的速率产生低于它的层。",
    "Each unit tier's base unit multiplier is equal to its corpse multiplier, instead of the square root.": "每个单位层的基本单位乘数等于其尸体乘数，而不是平方根。",
    "effect squared also applies to the production of corpses and astral bricks.": "效果平方也适用于尸体和星界砖的生产。",
    "effect.": "影响。",
    "Effects that apply to \"corpse production\" don't affect this.": "适用于“尸体生产”的效果不会影响这一点。",
    "ENABLE HOTKEYS: ON": "启用热键：开",
    "Ethereal Upgrades": "空灵升级",
    "Even in your godlike state this is beyond you. This will require study.": "即使在你神一样的状态下，这也超出了你的范围。这将需要研究。",
    "Even-numbered refinery levels give one additional emitter.": "偶数精炼厂级别提供了一个额外的发射器。",
    "Every completion rewards 1 Impossible Theorem. Each unspent theorem raises the exterminated worlds effect to ^1.2, and they are used to buy Ethereal Upgrades.": "每次完成都会奖励 1 个不可能定理。每个未使用的定理都会将灭绝世界效应提高到 ^1.2，并且它们用于购买虚灵升级。",
    "Exp. cost scaling for all construction upgrades starts 10 levels later (after 3.22).": "经验。所有建筑升级的成本缩放在 10 个级别后开始（3.22 之后）。",
    "Exponential cost scaling for all construction upgrades starts at level 1.": "所有建筑升级的指数成本缩放从级别 1 开始。",
    "Exponential cost scaling for all units starts after twice as many bought.": "所有单位的指数成本缩放在购买数量增加一倍后开始。",
    "Exponential cost scaling for the first four construction upgrades starts after twice as many levels.": "前四个建筑升级的指数成本缩放在两倍的级别之后开始。",
    "Export Galaxies": "导出星系",
    "EXPORT SAVE": "导出存档",
    "exterminated worlds": "灭绝的世界",
    "f: Cycle Subtabs;": "f：循环子选项卡；",
    "Factory Expansion": "工厂扩建",
    "forces a sacrifice reset": "强制牺牲重置",
    "Forgotten Worlds": "被遗忘的世界",
    "FORMULA TOOLTIPS: OFF": "公式工具提示：关闭",
    " at a time": " 一次",
    " congratulations. you have gone beyond.": "祝贺。你已经超越了。",
    " continue your domination?": " 继续你的统治？",
    " if you see this for more than a few seconds, something's wrong. please contact the dev on": " 如果您看到此内容超过几秒钟，则说明有问题。请联系开发人员",
    " You gained": " 你获得了",
    ", and similar games.": "，以及类似的游戏。",
    ", boosting all units' corpse multipliers by": ", 将所有单位的尸体乘数提高",
    ", giving a": "，给出一个",
    ", jacorb's": ", 雅各布的",
    ", raising the exterminated worlds effect to ^": ", 将灭绝世界效应提升到 ^",
    ", raising time crystal gain to ^": ", 提高时间晶体增益到 ^",
    ". As a result, your base astral brick production is square rooted, but you produce Void Research at the same base rate.": ".结果，您的基础星体砖产量是平方根，但您以相同的基础速率生产虚空研究。",
    "\"Make yourself an ark of astral matter; make rooms in the ark, and cover it inside and outside with time.\"": "“让你自己成为一个星光物质的方舟；在方舟中建造房间，并用时间覆盖它的内外。”",
    "\"We have found you worthy of our ranks, small one.\"": "“我们发现你配得上我们的队伍，小个子。”",
    "(based on your bought sun eaters": "（基于您购买的日蚀者",
    "(based on your zombies": "（基于你的僵尸",
    "(softcapped at": "（软顶在",
    "A galaxy respec resets all costs to 1, and unlocks all locked upgrades.": "星系重洗 将所有成本重置为 1，并解锁所有锁定的升级。",
    "a: Toggle Astral Enslavement;": "a：切换星体奴役；",
    "Abominable Steroids": "可恶的类固醇",
    "abominations": "憎恶",
    "Abominations": "憎恶",
    "achievements": "成就",
    "ACHIEVEMENTS": "成就",
    "achievements and": "成就和",
    "Achievements with a '+' have an additional reward; hover to view requirements and rewards.": "带“+”的成就有额外奖励；悬停查看要求和奖励。",
    "acolytes": "追随者",
    "acolytes.": "追随者。",
    "Add .02 per level to the armament gain exponent.": "武器增益指数每增加 0.02。",
    "Add .02 per level to the exponent of the exterminated worlds boost to corpse gain.": "每级增加 0.02 到灭绝世界的指数增加尸体增益。",
    "Additionally, galaxy upgrade costs are tripled (after the cost increase from higher rows), and": "此外，星系升级成本增加了三倍（在更高行的成本增加之后），并且",
    "after x seconds": "x 秒后",
    "All effects based on total galaxies are softcapped at": "基于总星系的所有影响都被软封顶",
    "All galaxy upgrades have a base cost of": "所有星系升级的基本成本为",
    "All Time": "整天",
    "All unit tier corpse multipliers are raised to the ^0.9.": "所有单位层的尸体乘数都提高到 ^0.9。",
    "All unit tier corpse multipliers are raised to the ^1.1.": "所有单位层的尸体乘数都提高到 ^1.1。",
    "amount": "数量",
    "ancient ones": "古人",
    "Ancient Ones": "古人",
    "and": "和",
    "and contains": "并包含",
    "and they multiply": "他们成倍增加",
    "andromeda": "仙女座",
    "Andromeda": "仙女座",
    "Andromeda/Circinus": "仙女座/圆环",
    "ANTI": "反",
    "Anti Time Emitters": "反时间发射器",
    "anti time essence.": "反时间本质。",
    "Antimatter Dimensions": "反物质维度",
    "Arm your zombies, giving a boost to their corpse multiplier based on armaments.": "武装你的僵尸，以武器为基础提高他们的尸体乘数。",
    "armaments": "军备",
    "Build the": "建造",
    "disable": "点击禁用",
    "you have": "你有 ",
    "enable": "点击启用",
    "Achievement Unlocked!": "成就已达成！",
    "Are You Sure?": "你确定吗？",
    "CLOSE HELP": "关闭帮助",
    "corpse": "尸体",
    "LAST 10 SAC.": "最近 10 牺牲",
    "NO": "否",
    "REFINERY": "精炼厂",
    "Respec emitters - forces sacrifice": "重洗发射器 - 强制牺牲",
    "These confirmations can be disabled in options": "这些确认可以在选项中禁用",
    "This will reset ALL of your corpses, units, and astral bricks.": "这将重置你所有的尸体、单位和星界砖。",
    "This will reset ALL of your progress before unlocking Time Warp, and all of your time essense.": "这将在解锁时间扭曲之前重置您的所有进度，以及您所有的时间本质。",
    "YES": "是的",
    "armament": "军备",
    "astral brick": "星体砖",
    "Anti Time Emitter": "反时间发射器",
    "This Sacrifice": "这个牺牲",
    "This world prestige will unlock Buildings and a new unit tier.": "这种世界声望将解锁建筑物和新的单位等级。",
    "Time Emitter": "时间发射器",
    "This world prestige will unlock Construction and a new unit tier.": "这个世界声望将解锁建筑和新的单位等级。",
    "world": "世界",
    "10 exterminated worlds are required to ascend for one galaxy. The formula for further gain is floor(x^(x/10 - sqrt(x/10))). When you perform an ascension, everything up to the point that you unlocked galaxies is reset. The ONLY things                     other than achievements that you keep after your first ascension are": "一个星系需要 10 个已灭绝的世界才能上升。 进一步增益的公式是 floor(x^(x/10 - sqrt(x/10)))。 当你执行提升时，直到你解锁星系的所有东西都会被重置。 在你第一次扬升之后，除了成就之外，你唯一能保持的东西是",
    "(more sections will appear here as you progress": "（随着您的进展，更多部分将出现在此处",
    "(the upgrade that unlocks galaxies), the prestige autobuyer, and the fast/bulk/advanced autobuyer upgrades (but you still need to buy": "（解锁星系的升级），声望自动购买，以及快速/批量/高级自动购买升级（但你仍然需要购买",
    "again before you can use autobuyers).": "在你可以使用自动购买之前再次）。",
    "All tabs (buildings, construction, time dimensions, time upgrades, and autobuyers) stay unlocked.": "所有选项卡（建筑物、建筑、时间维度、时间升级和自动购买者）保持解锁状态。",
    "Astral brick production is square rooted, but during astral enslavement, you produce Void Research at the same base rate (sqrt(corpse_production^0.2)).": "星界砖的生产是平方根的，但在星界奴役期间，你以相同的基本速率生产虚空研究 (sqrt(尸体生产^0.2))。",
    "Astral bricks": "星体砖",
    "AUTOBUYERS": "自动购买者",
    "Buildings": "建筑物",
    "BUILDINGS": "建筑",
    "CONSTRUCTION": "构造",
    "Construction upgrades": "建筑升级",
    "Corpses": "尸体",
    "Cosmogenesis": "宇宙发生",
    "Cost multipliers by dimension tier: 10, 100, 100, 1000.": "按维度层的成本乘数：10、100、100、1000。",
    "Cost multipliers by unit tier (first tier = zombies): 100, 1e4, 1e4, 1e6, 1e10, 1e11, 1e12, 1e15.": "单位层的成本乘数（第一层 = 僵尸）：100、1e4、1e4、1e6、1e10、1e11、1e12、1e15。",
    "DEAD SUN": "死太阳",
    "Dead Sun upgrades are purchased with nekro-photons and mostly unlock new upgrades and features.": "死日 升级是用 死光子 购买的，主要是解锁新的升级和功能。",
    "Death Factory upgrades are purchased with armaments and will improve the effects of your units.": "死亡工厂升级与武器一起购买，将提高你单位的效果。",
    "DEPLETED GALAXIES": "耗尽的星系",
    "During a research project": "在研究项目期间",
    "FACTORY": "工厂",
    "Final note: the Time Essence effects don't apply at all to time dimensions or essence production, and neither does the time speed nerf from Astral Enslavement.": "最后一点：时间精华效果根本不适用于时间维度或精华生产，也不适用于星界奴役的时间速度削弱。",
    "Finally, there are galaxy milestones. These are permanent rewards that you receive the first time you fully complete 1/2/3/4 galaxies at once. NOTE: the milestones window is draggable.": "最后，还有星系里程碑。 这些是您第一次一次完全完成 1/2/3/4 个星系时获得的永久奖励。 注意：里程碑窗口是可拖动的。",
    "Galaxies": "星系",
    "Galaxy upgrade costs are tripled, AFTER the increase in price from other bought upgrades.": "在其他购买的升级价格上涨之后，星系 升级成本增加了两倍。",
    "Here you buy undead creatures with corpses.": "在这里，您可以购买带有尸体的不死生物。",
    "Units": "单位",
    "UNITS": "单位",
    "VOID RESEARCH": "虚空研究",
    "How To Play Nekromantik": "如何玩 死灵术2",
    "INFINITE RESEARCH": "无限研究",
    "World Stasis 3": "世界静止 3",
    "Refinery": "精炼厂",
    "REFINERY": "精炼厂",
    "THE ARK": "方舟",
    "NECROPOLIS": "大墓地",
    "Necropolis upgrades are purchased with astral bricks, and increase their effectiveness.": "墓地升级是用星体砖购买的，并提高了它们的效率。",
    "NEW WORLDS": "新世界",
    "Time crystals": "时间水晶",
    "Time upgrades": "时间升级",
    "TIME UPGRADES": "时间升级",
    "The sacrifice autobuyer works a bit differently. You specify at what amount of crystals gained it should sacrifice, and then every autobuyer tick it will check your crystal gain and sacrifice if it's greater than                     or equal to what you entered. There is an additional checkbox on the sacrifice autobuyer for \"auto lock in\"; this means if the sacrifice was initiated by the autobuyer, it will automatically lock in your time                     dimensions to start producing essence.": "牺牲自动购买者的工作方式有点不同。 你指定它应该牺牲多少获得的水晶，然后每个自动购买者勾选它会检查你的水晶增益，如果它大于或等于你输入的内容，则牺牲。 在牺牲自动购买者上有一个额外的复选框，用于“自动锁定”； 这意味着如果牺牲是由自动购买者发起的，它将自动锁定您的时间维度以开始生产精华。",
    "Now that you have your first galaxy, you can spend it on a galaxy upgrade. There are four separate galaxy trees, and each has two branches in the middle. You can only take one brach at a time; buying a 2nd row upgrade in any galaxy                     will immediately lock out the two upgrades in that galaxy's other branch. Each upgrade has a base cost of 1 galaxy, but any time you buy an upgrade, the costs of all upgrades in all rows below it are increased by 1, and buying a 4th row                     upgrade increases the first row's costs by 1. A galaxy respec will completely reset all galaxy upgrades, costs, and locked upgrades.": "现在您有了第一个星系，您可以将其用于星系升级。 有四棵独立的星系树，每棵树的中间都有两个分支。 一次只能取一根； 在任何星系购买第二排升级将立即锁定该星系另一个分支中的两个升级。 每次升级的基本成本为 1 个星系，但无论何时购买升级，其下方所有行的所有升级成本都会增加 1，购买第 4 行升级会使第一行的成本增加 1。 将完全重置所有星系升级、成本和锁定升级。",
    "Time Dimensions work similarly to units, except there are only 4 tiers. Each 1st dimension produces 1 time essence per second times the 1st dimension multiplier, which doubles with each 1st dimension purchased. Each higher tier dimension produces 1 per second of the tier below it,                     multiplied by that tier's multiplier. Unlike units, each dimension's multiplier increases at the same rate (x2 with each purchase) and the full multiplier is applied to production; however, the higher tier multipliers don't apply directly to essence production.": "时间维度的工作方式与单位类似，但只有 4 层。 每个 1 维每秒产生 1 个时间精华乘以 1 维乘数，每购买一个 1 维，乘数就翻倍。 每个更高的层维度每秒产生 1 个低于它的层，乘以该层的乘数。 与单位不同，每个维度的乘数以相同的速度增加（每次购买 x2），并且整个乘数应用于生产； 然而，更高等级的乘数并不直接应用于精华生产。",
    "True Time Essence increases the multiplier to normal time speed, while Anti Time Essence increases the multiplier to time speed during Astral Enslavement. The Anti Time Essence boost is twice as powerful as the True Time Essence boost.                     True Time Essence also divides the Anti Time Essence effect, and vice versa, so you receive the strongest boost for either by setting the slider all the way to one side, but then you won't receive any boost at all for the Essence that isn't producing.": "真实时间精华增加正常时间速度的乘数，而反时间精华增加星体奴役期间的时间速度乘数。 反时间精华提升 是 真实时间精华提升 的两倍。 真实时间精华 还划分了 反时间精华 效果，反之亦然，因此通过将滑块一直设置到一侧，您将获得最强的提升，但您将不会收到任何提升 不生产。",
    "To gain Time Crystals, you need to Sacrifice. You need at least 1e20 corpses to sacrifice, and it will reset ALL of your progress up to unlocking Refinery (your corpses, units, exterminated worlds,                     astral bricks, buildings, building upgrades, and construction upgrades) plus any time essence or time dimensions you've produced (not bought). You will gain time crystals based on the amount of corpses you have when you sacrifice. (base formula is floor(10^(corpses_exponent/20 - 0.45))": "要获得时间水晶，您需要牺牲。 你需要至少 1e20 具尸体来牺牲，它会重置你的所有进度，直到解锁精炼厂（你的尸体、单位、灭绝的世界、星体砖、建筑物、建筑升级和建筑升级）以及你的任何时间本质或时间维度 '已经生产（未购买）。 你会根据你牺牲时拥有的尸体数量获得时间水晶。 （基本公式为 floor(10^(尸体指数/20 - 0.45))",
    "Each time autobuyers trigger, they attempt to buy each unit in order of the priority drop-down menus, starting with 1 and ending with 8.                    You will also eventually unlock \"bulk autobuyers\" for units, which attempt to max buy each unit every time instead of just buy one, and a world prestige autobuyer, which works the same as the unit autobuyers. You can toggle whether the game will prioritize prestige or sacrifice when they're both on and ready in the same tick.": "每次自动购买者触发时，他们都会尝试按照优先级下拉菜单的顺序购买每个单位，从 1 开始，以 8 结束。您最终还将为单位解锁“批量自动购买者”，这会尝试最大程度地购买每个单位 每次都不是只买一个，而是一个世界知名的自动购买者，其工作方式与单位自动购买者相同。 您可以切换游戏是否会优先考虑声望或牺牲，当它们同时开启并准备好时。",
    "Each unit also has a corpse multiplier that multiplies your total corpse gain (additively), and a unit multiplier, which multiplies the unit production of that tier and each tier below it. (additively).                     Every time you purchase one of a unit after the first, its cost and corpse multiplier are multiplied by constants. The base unit multiplier is always equal to the square root of the corpse multiplier.": "每个单位还有一个尸体乘数，可以乘以你的总尸体增益（加法），还有一个单位乘数，可以乘以该层及其以下每个层的单位产量。 （另外）。 每次您在第一个单位之后购买一个单位，其成本和尸体乘数都会乘以常数。 基本单位乘数始终等于尸体乘数的平方根。",
    "Each autobuyer attempts to purchase its corresponding unit or reset at regular intervals. When you first unlock them, you only have access to \"slow autobuyers\" - these trigger every 15 REAL WORLD seconds,                     meaning the time speed effects from astral enslavement and time essence have no effect on that interval. Eventually, you'll unlock \"fast autobuyers\", which trigger every game tick (20x/sec).": "每个自动购买者都会尝试购买其相应的单位或定期重置。 当你第一次解锁它们时，你只能访问“缓慢的自动购买者”——它们每 15 秒触发一次，这意味着来自星体奴役和时间本质的时间速度效果对该间隔没有影响。 最终，您将解锁“快速自动购买者”，它会触发每个游戏滴答（20 次/秒）。",
    "Lastly, you will eventually unlock more options for the sacrifice autobuyer's condition. The two additional ones are: \"at x times last\", which sacrifices when your crystal gain is at least x times the amount of crystals                     gained in your last sacrifice, and \"after x seconds\", which simply sacrifices the specified number of seconds after your last sacrifice.": "最后，您最终将为牺牲自动购买者的条件解锁更多选项。 另外两个是：\"至少 x 次\"，当你的水晶增益至少是你最后一次牺牲中获得的水晶数量的 x 倍时牺牲，以及 \" x 秒后\"，它只是牺牲指定的 你最后一次牺牲后的秒数。",
    "Infinite research has all the same effects as Research Project 6, but your corpse production is raised to ^0.9 a second time. The starting goal is 1e16 Void Research. You can complete Infinite Research unlimited times, but the research goal is multiplied by 10 for each completion.                     Each completion also raises your time crystal gain to ^1.01 (multiplicatively).": "无限研究与研究计划 6 具有相同的效果，但您的尸体产量第二次提高到 ^0.9。 起始目标是 1e16 虚空研究。 您可以无限次完成无限研究，但每次完成研究目标乘以 10。 每次完成还会将您的时间晶体增益提高到 ^1.01（乘法）。",
    "To complete a research project, you must reach that project's goal in Void Research. Completing a project performs a galaxy respec WITHOUT forcing an ascension reset and unlocks the corresponding ark component and project reward. Each project completed also doubles the number of galaxies that the galaxy effect softcaps begin at.": "要完成一个研究项目，您必须在虚空研究中达到该项目的目标。 完成一个项目会执行一个星系 重洗 而不会强制重置提升并解锁相应的方舟组件和项目奖励。 每个完成的项目也会使星系效应软帽开始时的星系数量增加一倍。",
    "Each project has a unique effect that is applied in addition to these.": "除了这些之外，每个项目都有一个独特的效果。",
    "Each zombie produces one corpse per second directly, while all other units produce the unit one tier below them at a rate of 1/tier per unit per second.": "每个僵尸每秒直接产生一具尸体，而所有其他单位以每秒每单位 1 个/层的速度产生比它们低一级的单位。",
    "Enabling Astral Enslavement disables corpse production and slows down time by 10x. During this time, you gain Astral Bricks based on your                     corpse gain (base formula is corpse gain^0.2).": "启用星界奴役会禁用尸体生产并将时间减慢 10 倍。在此期间，你会根据你的尸体增益获得星界砖（基本公式是尸体增益^0.2）。",
    "Even in your godlike state, the plans for The Ark are beyond you. You must put your enslaved souls to work studying and deciphering them.": "即使在你神一样的状态下，方舟的计划也超出了你的范围。你必须让你被奴役的灵魂去研究和破译它们。",
    "Eventually, this world will run out of souls to torture and corpses to harvest. When this happens, you must 'world prestige' to move on to a new world.": "最终，这个世界将没有灵魂可供折磨，没有尸体可供收割。发生这种情况时，您必须获得“世界声望”才能进入新世界。",
    "Every time you complete an infinite research, you gain 1 Impossible Theorem. You can use these to buy Ethereal Upgrades, and each unspent theorem raises the exterminated worlds effect to ^1.2 (multiplicatively). Ethereal upgrades can be respecced at any time, but this forces a sacrifice reset.": "每次完成无限研究时，您都会获得 1 个不可能定理。您可以使用这些来购买以太升级，并且每个未使用的定理都会将灭绝世界效应提高到 ^1.2（乘法）。空灵升级可以随时进行，但这会强制重置牺牲。",
    "Here you can use Astral Bricks to improve the infrastructure of your hellish empire machine. These upgrades can be bought repeatedly and indefinitely, although the cost                     increases exponentially at high levels (>25).": "在这里，您可以使用 Astral Bricks 来改善您的地狱帝国机器的基础设施。这些升级可以无限期地重复购买，尽管成本在高水平（> 25）呈指数增长。",
    "Here you will forge Astral Bricks and use them to construct monstrous buildings of death and war. Each building generates its own resource, and has its own set of upgrades                     focused on one aspect of the game.": "在这里，您将锻造星界砖，并用它们来建造可怕的死亡和战争建筑。每栋建筑都会产生自己的资源，并针对游戏的一个方面进行自己的升级。",
    "Here you will produce armaments for your savage hordes. The production rate is based on the number of zombies you have (base formula is log10(zombies+1)^0.5) - someone needs to work the factory, after all.": "在这里，您将为您的野蛮部落生产武器。生产率取决于你拥有的僵尸数量（基本公式是 log10(zombies+1)^0.5）——毕竟有人需要在工厂工作。",
    "Here you will produce nekro-photons. They are produced at a constant rate, but only during astral enslavement (and yes, they are affected by the astral time speed nerf, but also by anti time essence).": "在这里，您将产生 死光子。它们以恒定的速率产生，但仅限于星界奴役期间（是的，它们受到星界时间速度削弱的影响，但也受到反时间本质的影响）。",
    "Here you will use Time Crystals to purchase Time Dimensions, which produce Time Essence in two varieties - True Time and Anti Time.": "在这里，您将使用时间水晶购买时间维度，它会产生两种时间精华 - 真实时间和反时间。",
    "Here you'll buy some very powerful upgrades with Time Crystals. This is the point where you'll start needing to sacrifice frequently and repeatedly to make significant progress, so most of these                     upgrades focus on making sacrifice runs go faster.": "在这里，您将使用时间水晶购买一些非常强大的升级。这是您开始需要频繁且反复牺牲以取得重大进展的点，因此这些升级中的大多数都专注于使牺牲运行更快。",
    "Multiplier multipliers by unit tier: 1.75, 2, 2, 2, 2.2, 2.2, 2.5, 2.5.": "按单位层的乘数乘数：1.75、2、2、2、2.2、2.2、2.5、2.5。",
    "Note: clicking the \"respec slider\" button only counts as a sacrifice (for boosts/achievements based on number of sacrifices) if you actually gain time crystals. If you click the respec button before you reach 1e20 corpses, it won't be counted.": "注意：如果您确实获得了时间水晶，则单击“respec滑块”按钮仅计为牺牲（对于基于牺牲数量的提升/成就）。如果您在到达 1e20 个尸体之前单击 respec 按钮，则不会计算在内。",
    "Of course, if you wish, you can continue your sinister campaign indefinitely.": "当然，如果你愿意，你可以无限期地继续你的险恶战役。",
    "Production of corpses, building resources, time dimensions, and time essence are raised to ^0.9.": "尸体生产、建筑资源、时间维度、时间精华提升至^0.9。",
    "The first four world prestiges require at least one of your highest unlocked unit tier. After that, the requirement in 8th tier units increases by 2 with every prestige.": "前四个世界声望至少需要您的最高解锁单位等级之一。之后，第 8 层单位的要求每增加 2 个声望。",
    "The fourth and fifth columns of time upgrades and the Galactic Vortex/black holes are not reset, but they have no effect during research.": "第四和第五列时间升级和银河漩涡/黑洞没有重置，但在研究过程中没有效果。",
    "There are six research projects, and each unlocks one of the six ark components. Starting a research project inflicts several negative effects:": "有六个研究项目，每个项目都解锁六个方舟组件之一。开始一个研究项目会产生几个负面影响：",
    "They send you what appear to be blueprints for a vessel - a vessel to travel beyond the borders of this reality. It may as well be gibberish, for now.": "他们向你发送似乎是一艘船只的蓝图——一艘超越现实边界的船只。就目前而言，它也可能是胡言乱语。",
    "When you start a project, you do a galaxy respec and a time respec. However, ALL of the following are reset to their starting state/value, regardless of rewards from acheivements/milestones/projects": "当你开始一个项目时，你会做一个星系respec和一个时间respec。但是，无论来自成就/里程碑/项目的奖励如何，以下所有内容都将重置为其初始状态/值",
    "When you world prestige, you lose all of your corpses and units, and you gain one Exterminated World. Your exterminated worlds provide a new multiplier to total corpse gain. Your first three world prestiges                     each also unlock a new feature and a new unit tier.": "当你获得世界声望时，你会失去所有的尸体和单位，并获得一个灭绝世界。你被灭绝的世界为总尸体收益提供了一个新的乘数。你的前三个世界声望也解锁了一个新功能和一个新的单位等级。",
    "You are called from beyond by a cabal of beings of unimaginable power. They have recognized you power, and want to recruit you into their ranks. This is the culmination of all your labors: true extinction of this universe, and power unlimited.": "你被一群拥有难以想象的力量的生物召唤而来。他们已经认识到你的力量，并想招募你加入他们的行列。这是你所有努力的成果：这个宇宙的真正灭绝，以及无限的力量。",
    "You can set the percentage of production from Time Dimensions put towards True/Anti Time Essence however you'd like, but you can't change this setting without doing a sacrifice reset. You won't start Time Essence production until you click \"lock in\", which will disable the slider.": "您可以根据需要设置从时间维度到真/反时间精华的生产百分比，但是如果不进行牺牲重置，则无法更改此设置。在您单击“锁定”之前，您不会开始 Time Essence 制作，这将禁用滑块。",
    "You have deciphered the plans for The Ark, but your thirst for impossible knowledge has only increased. You continue delving deeper into the unknowable mysteries of The Beyond, with Infinite Research.": "你已经破译了方舟的计划，但你对不可能的知识的渴望只会增加。您将继续通过 无限研究 深入探究 超越 的不为人知的奥秘。",
    "You have exterminated countless worlds, and your power begins to reach a point of singularity. You gather your energies and A S C E N D, forming a putrid, macabre Depleted Galaxy from the remains of those empty worlds.": "你消灭了无数世界，你的力量开始达到一个奇点。你聚集你的能量和 A S C E N D，从那些空荡荡的世界的残骸中形成一个腐烂、令人毛骨悚然的耗尽星系。",
    "You must compelete Void Research Projects to unlock each component of the ark. Once unlocked, you spend both astral bricks and time crystals to build them. Once you've built all six components, you win the game.": "您必须完成虚空研究项目才能解锁方舟的每个组件。解锁后，您将花费星体砖和时间水晶来建造它们。一旦你构建了所有六个组件，你就赢得了比赛。",
    "Your Necropolis trains acolytes to assist in channelling the astral void. The energies required to imbue mere mortals with this power is staggering, so you can only gain acolyte": "你的墓地训练侍僧来协助引导星界虚空。将这种力量灌输给凡人所需的能量是惊人的，所以你只能获得追随者",
    "Your Necropolis trains acolytes to assist in channelling the astral void. The energies required to imbue mere mortals with this power is staggering, so you can only gain acolytes                     while you control the most powerful of undead beasts - the Sun Eaters (base formula is sun eaters^2).": "你的墓地训练侍僧来协助引导星界虚空。 将这种力量灌输给普通人所需的能量是惊人的，因此您只能在控制最强大的不死野兽 - 日蚀者（基本配方为日蚀者^2）时获得追随者。",
    ", only during astral enslavement.": "，仅在星体奴役期间。",
    "acolyte": "追随者",
    "completed row": "完成的行",
    "Death Factory Expansion": "死亡工厂扩张",
    "Frugality": "节俭",
    "Galactic Angst": "银河焦虑",
    "I Need To Go Faster": "我需要走得更快",
    "Master Nekro-Carpenter": "死灵木匠大师",
    "Necropolis Expansion": "墓地扩张",
    "nekro-photon": "死光子",
    "Nekro-photon production is disabled outside of astral enslavement.": "死灵光子的产生在星体奴役之外被禁用。",
    "nekro-photons": "死光子",
    "Nekro-Time": "死灵时间",
    "sun eaters": "日蚀者",
    "The Grind": "研磨",
    "This upgrade is never reset on sacrifice.": "此升级永远不会因牺牲而重置。",
    "Unlock a new row of Death Factory upgrades.": "解锁一排新的死亡工厂升级。",
    "Unlock a new row of Necropolis upgrades.": "解锁新的墓地升级行。",
    "Unlock time upgrades.": "解锁时间升级。",
    "Arm The Dead": "武装死者",
    "Armament production is boosted based on abominations.": "武器生产基于憎恶而提高。",
    "Astral Fusion": "星体融合",
    "Astral Kiln Kilns": "星界窑炉",
    "Astral Magnifying Glass": "星体放大镜",
    "Boost astral brick production based on astral bricks.": "以星界砖为基础提高星界砖的产量。",
    "Boost nekro-photon production based on astral bricks.": "提高基于星体砖的死灵光子产量。",
    "Corpse production is boosted based on corpses.": "尸体生产是基于尸体提升的。",
    "Galactic Armaments": "银河军备",
    "Get free time emitters based on your best astral bricks.": "根据你最好的星体砖获得空闲时间发射器。",
    "Part Time Jobs": "兼职工作",
    "The sun eater corpse multiplier is multiplicative instead of additive when it's greater than 1x.": "当它大于 1 倍时，噬日者尸体乘数是乘法而不是加法。",
    "True Time Emitter": "真实时间发射器",
    "TIME REFINERY": "时间精炼厂",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'DISCORD': 'DISCORD',
    'discord': 'discord',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t\t": "\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "World Stasis ": "世界停滞 ",
    "Project ": "项目 ",
    "Buy max (": "购买最大 (",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "time crystals": "时间水晶",
    "astral bricks": "星体砖",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Requires (.+) sun eater$/, '需要 $1 个日蚀者'],
    [/^Requires (.+) sun eaters$/, '需要 $1 个日蚀者'],
    [/^Requires (.+) ancient one$/, '需要 $1 个古人'],
    [/^Requires (.+) lich$/, '需要 $1 个巫妖'],
    [/^Requires (.+) behemoth$/, '需要 $1 个巨兽'],
    [/^Avg. of past 10 runs: (.+); (.+) crystals; (.+) crystals\/min$/, '平均过去 10 次游戏时长：$1； $2 水晶； $3 水晶/分钟'],
    [/^(.+) crystals; (.+) crystals\/min$/, '$1 水晶； $2 水晶\/分钟'],
    [/^your best crystal gain was (.+) and your best crystal gain rate was (.+)\/min$/, '您的最佳水晶增益为 $1，您的最佳水晶增益率为 $2\/分钟'],
    [/^you have world prestiged (.+) times$/, '你世界声望了 $1 次'],
	[/^\/ ascended (.+) times$/, '\/ 转生了 $1 次'],
	[/^\/ sacrificed (.+) times$/, '\/ 牺牲了 $1 次'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) exterminated world$/, '$1 灭绝的世界'],
	[/^([\d\.,]+) nekro-photons$/, '$1 死光子'],
	[/^([\d\.,]+) armaments$/, '$1 军备'],
	[/^([\d\.,]+) corpses$/, '$1 尸体'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) impossible theorem$/, '$1 不可能定理'],
	[/^([\d\.]+) galaxy$/, '$1 星系'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+)e([\d\.,]+) corpses$/, '$1e$2 尸体'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Goal: (.+) Void Research$/, '目标：$1 虚空研究'],
    [/^Current Goal: (.+) Void Research$/, '当前目标：$1 虚空研究'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Level: (\d+)$/, '等级：$1'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);